name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip
    - name: Authenticate Ngrok
      run: |
        .\ngrok\ngrok.exe authtoken 2dEYlYZXlwnX4pR3IPCcsKcTeWF_8rrFGD3W2xTdjJ8t2xZE || exit 1
    - name: Enable Terminal Server
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - name: Set Local User Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: |
        echo "tunnels:" | Out-File -FilePath .\ngrok\ngrok.yml -Encoding utf8
        echo "  rdp:" | Out-File -FilePath .\ngrok\ngrok.yml -Append -Encoding utf8
        echo "    proto: tcp" | Out-File -FilePath .\ngrok\ngrok.yml -Append -Encoding utf8
        echo "    addr: 3389" | Out-File -FilePath .\ngrok\ngrok.yml -Append -Encoding utf8
        .\ngrok\ngrok.exe start --all --config .\ngrok\ngrok.yml
